name: Semantic Release

on:
  push:
    branches:
      - main

permissions:
  contents: write # to be able to publish a GitHub release
  pull-requests: write # to be able to comment on released pull requests
  issues: write # to be able to comment on released issues

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Release
        uses: cycjimmy/semantic-release-action@v4.1.1
        with:
          semantic_version: 24.2.3
          extra_plugins: |
            conventional-changelog-conventionalcommits@8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
